# Generated by Django 5.1.6 on 2025-03-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Store", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
