# Generated by Django 5.1.6 on 2025-03-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Store", "0004_remove_profile_profile_picture_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="pic",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="profile_pics/"
            ),
        ),
    ]
